environment:
  # Note: Casing doesn't matter for environment values - using mixed case for consistency
  - default/byoc-YOUR_ORG_ID_MIXED_CASE_HERE

config:
  # EKS Configuration
  eksClusterName: boreal-byoc-eks-cluster
  eksPrivateEndpointEnabled: true
  eksPublicEndpointEnabled: true

  # Jump Box Configuration
  jumpboxEnabled: true
  jumpboxName: boreal-byoc-jump-box
  jumpboxInstanceType: t3.micro
  # tailscaleAuthKey is pulled from the ESC environment

  # Tailscale Configuration
  tailscaleOperatorHostname: aws-YOUR_ORG_NAME_HERE-tailscale-operator-us-east-2
  createTailscaleSubnetRouter: false # Set to true to advertise VPC CIDR to Tailscale network
  # tailscaleClientId: ""  # pulled from the ESC environment
  # tailscaleClientSecret: ""  # pulled from the ESC environment
